language: java

script:
  # other script steps might be done before running the actual analysis
  - mvn test -B
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn sonar:sonar -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=$SONAR_KEY -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.sources=./src -Dsonar.exclusions=**/**.ucls,**/**.xml -Dsonar.tests=./test -Dsonar.language=java -Dsonar.java.binaries=. -Dsonar.java.libraries=./TartanAdventure_jar -Dsonar.java.test.binaries=./test -Dsonar.java.test.libraries=./TartanAdventure_jar  -Dsonar.verbose=true -Dsonar.dynamicAnalysis=reuseReports -Dsonar.junit.reportsPath=target/surefire-reports -Dsonar.java.coveragePlugin=jacoco -Dsonar.jacoco.reportPaths=target/jacoco.exec; fi
